import Head from 'next/head';
import React from 'react';

const Layout: React.FC = ({ children }) => {
	return (
		<div>
			<div>
				<Head>
					<title>Create Next App</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>

				<main>{children}</main>
			</div>
		</div>
	);
};

export default Layout;
